### 회원가입
POST localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "userId": "hollys9152",
  "email": "kyun9153@gmail.com",
  "username": "김명균",
  "nickname": "1ahodumaru12233",
  "password": "a12345678",
  "passwordConfirm": "a12345678"
}

### 이메일 인증번호 보내기
POST localhost:8888/api/v1/emails/verification-requests?email=cbw60881@gmail.com

### 이메일 인증
GET localhost:8888/api/v1/emails/verify-code?email=cbw60881@gmail.com&code=XrbQuKDrYUNsYsOlKpxosGXt

### 로그인
POST 223.130.130.88/api/v1/login
Content-Type: application/json

{
  "userId": "user84363",
  "password": "12345678"
}

### 유저 개인정보
GET localhost:8080/api/v1/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI4ODg5NjAzfQ.UCGdmgxgufDoBjcRkFG9F8D2hLI-6CTfQyPRDKr9RwU0MYf3kvJBXXHrxTi6ooXrnQ2oihGVGuCfFLkIUK75Aw

### 유저 정보 수정
PUT localhost:8080/api/v1/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE3Mjg1NTUyODF9.Cy2xMu5Zxkh2F4SCAHV0FhMGIobR1fcOzFfVaC2OjuLqCG0BT5LETr4-UbHS9TSzA_vszBLrWimuAqD8xvPk9Q

{
  "userId": "kyun9151",
  "email": "kyun9151@gmail.com",
  "username": "김명균",
  "nickname": "hodumaru123"
}

### 로그아웃
PATCH localhost:8080/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI0MDU2NTQzfQ.fItcs6-2yd4qwkZcfwyxE_-z3ErISwAauZEHWT_sZUOfkuDFhr9-TlAogMqsZju9RtOHZcpJ0SQKVN8GI2Sa_Q

### 아이디 찾기
GET localhost:8080/api/v1/find-user?email=20003214@sju.ac.kr

### 비밀번호 재설정
PUT localhost:8080/api/v1/find-pwd?email=kyun9151@gmail.com
Content-Type: application/json

{
  "password": "123456789",
  "passwordConfirm": "123456789"
}


### 전체 폴더정보
GET localhost:8080/api/v1/folders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI4ODg5NjAzfQ.UCGdmgxgufDoBjcRkFG9F8D2hLI-6CTfQyPRDKr9RwU0MYf3kvJBXXHrxTi6ooXrnQ2oihGVGuCfFLkIUK75Aw

### 폴더 정보
GET localhost:8080/api/v1/folder-info?folderId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI1MjU0NzM1fQ.EwGxT6Pi5nT9mAO9FIY3lqoo3irVFekH9u8nahNbAzk4K6HetAQGnABj3N7fkgHiGAg15CoX-QEajiIb-BoqAA

### 폴더생성
POST localhost:8888/api/v1/folders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE3Mjg1NTQ0OTd9.UKkctXme53KZr5MaGIhaiUer7rqhtJ5ONhzurpmcjXTbaeqLFoGSGv5Rh6OHCpwUNBi9Vbvgr-o2MJHXp8G6lw

{
  "folderName": "폴더2"
}

### 폴더삭제
DELETE localhost:8080/api/v1/folders?folderId=6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI0OTE0MDUyfQ.cejJpZyZ9o_2caEX_3PhDzG5lpA7P18321lE1Z0WYReVRl1k6lajVCyeAhp8Cvv9w-nFZ0E9viVSYlCBwBFXUQ

### 폴더정보변경
PUT localhost:8080/api/v1/folders?folderId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI0OTE0MDUyfQ.cejJpZyZ9o_2caEX_3PhDzG5lpA7P18321lE1Z0WYReVRl1k6lajVCyeAhp8Cvv9w-nFZ0E9viVSYlCBwBFXUQ

{
  "folderName": "김명균4"
}

### 푼 문제
GET localhost:8080/api/v1/exams-main
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI1MjU0NzM1fQ.EwGxT6Pi5nT9mAO9FIY3lqoo3irVFekH9u8nahNbAzk4K6HetAQGnABj3N7fkgHiGAg15CoX-QEajiIb-BoqAA

### 시험지 삭제
DELETE localhost:8080/api/v1/exams?examId=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI1MTg4NTMzfQ.EDDOax2yHQLEJUj3ZeWm-WBb-feGoQ_xAZJQ173ciHHKtqxRhxguYvLXtT_qwgf1DcCgD6tHbQFKTFNXizlBZw

### 시험지 폴더 이동
PUT localhost:8080/api/v1/exams?examId=1&folderId=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI1MjU0NzM1fQ.EwGxT6Pi5nT9mAO9FIY3lqoo3irVFekH9u8nahNbAzk4K6HetAQGnABj3N7fkgHiGAg15CoX-QEajiIb-BoqAA
