### 회원가입
POST localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "userId": "kyun9151",
  "email": "kyun9151@gmail.com",
  "username": "김명균",
  "nickname": "hodumaru",
  "password": "12345678",
  "passwordConfirm": "12345678"
}


### 로그인
POST localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "kyun9151@gmail.com",
  "password": "12345678"
}

### 유저 개인정보
GET localhost:8080/api/v1/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI0MjQ4NTM4fQ.5GbUVBuE8SidS1yLMBcfrpfcqXK8wKtMdSfXUweiP08Up3RodmlLSPhh3DVSci7m5mLIu8-8HeFAQABicSM7rw

### 로그아웃
PATCH localhost:8080/api/v1/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVuOTE1MUBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzI0MDU2NTQzfQ.fItcs6-2yd4qwkZcfwyxE_-z3ErISwAauZEHWT_sZUOfkuDFhr9-TlAogMqsZju9RtOHZcpJ0SQKVN8GI2Sa_Q

### 아이디 찾기
GET localhost:8080/api/v1/find-user?email=kyun9151@gmail.com