FROM ubuntu:20.04

# 시간대 설정 및 비대화형 설치 환경 설정
ENV TZ=Asia/Seoul
ENV DEBIAN_FRONTEND=noninteractive

# 필요한 라이브러리 설치
RUN apt-get update && apt-get install -y \
    poppler-utils \
    tesseract-ocr \
    tesseract-ocr-kor \
    tesseract-ocr-eng \
    libtesseract-dev \
    python3 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Python OCR 라이브러리 설치
RUN pip3 install pytesseract pdf2image pillow

# 작업 디렉토리 생성
WORKDIR /app

# 컨테이너 실행 시 계속 유지되도록 설정
CMD ["tail", "-f", "/dev/null"]